# Generated by Django 5.0.6 on 2024-06-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type_id', models.IntegerField(choices=[(0, 'Sin tipo'), (1, 'Panes'), (2, 'Tortas')], default=0)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
