# Generated by Django 5.0.6 on 2024-06-12 03:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_admin_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='idAdmin',
            field=models.UUIDField(default=uuid.UUID('f27730b6-286e-11ef-a416-ec63d7e5c5e9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
