# Generated by Django 5.0.6 on 2024-06-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_admin_idadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
